// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jabaddon.minitwitter.domain;

import com.jabaddon.minitwitter.domain.MTUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MTUser_Roo_Configurable {
    
    declare @type: MTUser: @Configurable;
    
}
